spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micromall
    username: mall
    password: cao19981128
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations:
    - classpath*:top/yu/mall/mapper/*.xml
    - classpth:dao/*.xml



redis:
  key:
    prefix: ums:authcode
    expire: 60  # 60s
auth:
  skip:
    urls:
      - /home/**
      - /sso/**
jwt:
  httpHeaderKey: Authorization
  secret: mall-member
  expire: 604800 # 60*60*24
  tokenHead: top.yu